# Generated by Django 6.0.3 on 2026-05-10 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action_type',
            field=models.CharField(choices=[('CREATE', 'Criação'), ('UPDATE', 'Atualização'), ('DELETE', 'Exclusão'), ('CANCEL', 'Cancelamento'), ('COMPLETE', 'Conclusão'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout')], max_length=30),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='entity_type',
            field=models.CharField(choices=[('CLASS', 'Turma/Aula'), ('HELP_CENTER', 'Centro de Ajuda'), ('MATERIAL', 'Material'), ('NOTICE', 'Aviso'), ('RESERVATION', 'Reserva'), ('USER', 'Usuário'), ('VENUE', 'Local/Espaço')], max_length=30),
        ),
    ]
