# Generated by Django 5.2.4 on 2026-06-26 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_logs', '0002_alter_activitylog_action_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action_type',
            field=models.CharField(choices=[('CREATE', 'Criação'), ('UPDATE', 'Atualização'), ('DELETE', 'Exclusão'), ('CANCEL', 'Cancelamento'), ('COMPLETE', 'Conclusão'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('USE', 'Uso'), ('RETURN', 'Devolução')], max_length=30),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='icon',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
