# Generated by Django 6.0.3 on 2026-05-10 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Agendado'), ('ONGOING', 'Em Andamento'), ('DONE', 'Concluído'), ('CANCELED', 'Cancelado')], default='SCHEDULED', max_length=30),
        ),
    ]
