# Generated by Django 6.0.3 on 2026-05-08 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('DIRECTOR', 'Diretoria'), ('TEACHER', 'Professor'), ('SUPPORT', 'Suporte')], default='TEACHER', max_length=20),
        ),
    ]
