# Generated by Django 6.0.3 on 2026-05-09 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venuestatus',
            name='name',
            field=models.CharField(choices=[('OPERATIONAL', 'Operacional'), ('MAINTENANCE', 'Em manutenção'), ('BLOCKED', 'Bloqueada')], default='OPERATIONAL', max_length=20),
        ),
    ]
