# Generated by Django 6.0.3 on 2026-05-09 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='class_days',
        ),
    ]
