# Generated by Django 6.0.3 on 2026-05-09 14:45

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_remove_class_class_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='class_days',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('MON', 'Segunda'), ('TUE', 'Terça'), ('WED', 'Quarta'), ('THU', 'Quinta'), ('FRI', 'Sexta'), ('SAT', 'Sábado'), ('SUN', 'Domingo')], max_length=3), default=list),
        ),
    ]
