# Generated by Django 5.2.4 on 2026-06-26 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_class_class_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classshift',
            name='name',
            field=models.CharField(choices=[('MORNING', 'Manhã'), ('AFTERNOON', 'Tarde'), ('EVENING', 'Noite'), ('INTEGRAL', 'Integral')], default='MORNING', max_length=20),
        ),
    ]
